services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: newsproject-redpanda
    ports:
      - "9092:9092"
      - "9644:9644"
    environment:
      - REDPANDA_AUTO_CREATE_TOPICS=true
    command: >
      redpanda start
      --overprovisioned
      --smp 1
      --memory 1G
      --reserve-memory 0M
      --node-id 0
      --kafka-addr PLAINTEXT://0.0.0.0:9092
      --advertise-kafka-addr PLAINTEXT://127.0.0.1:9092
